Modify firewalld check
The playbook used to fail in the absence of firewalld:

Error:
*********
TASK [Store all preflight check results]
fatal: [10.0.215.50]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'status'. 'dict object' has no attribute 'status'

This commit fixes Firewalld preflight check by handling missing or inactive service cases and improving error messages.

Fixes: https://tracker.ceph.com/issues/70525

Signed-off-by: Kushal Deb <Kushal.Deb@ibm.com>
(cherry picked from commit 3f0e6bd44aa7f4c9e6ba39a3d5d8123ea7866735)