Handle missing firewalld gracefully in preflight check
The playbook previously failed when the firewalld service was not installed
or active on the host, due to unguarded access to the 'status' attribute:

Error:
*******
TASK [Store all preflight check results]
fatal: [10.0.215.50]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was:
    'dict object' has no attribute 'status'. 'dict object' has no attribute 'status'

This commit updates the Firewalld preflight check to safely handle missing
or inactive firewalld service scenarios.

Fixes: https://tracker.ceph.com/issues/70702

Signed-off-by: Kushal Deb <Kushal.Deb@ibm.com>
(cherry picked from commit d8bcce3402c505bd36633e3b3ea414c972b09ff2)